name: Github Actions Demo

on: [push]

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "挨拶"
        run: echo "Nice to meet you!!"
      - name: "名前を言う"
        run: echo "My name is Taro!!"
      - name: "趣味を話す"
        run: echo "I love programming!!"
